ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 35, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 45, in main_loop
    current_button.on_click()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\actor_display_tools\buttons.py", line 1422, in on_click
    current_mob.start_suppress_slave_trade()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\group_types\battalions.py", line 464, in start_suppress_slave_trade
    print(risk_value)
UnboundLocalError: local variable 'risk_value' referenced before assignment
