ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 36, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 45, in main_loop
    current_button.on_click()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\actor_display_tools\buttons.py", line 1531, in on_click
    text_tools.print_to_screen('This village\'s rumors regarding the location of the ' + self.global_manager.get('current_lore_mission').name + ' have already been found.')
TypeError: print_to_screen() missing 1 required positional argument: 'global_manager'
