ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 35, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 211, in main_loop
    turn_management_tools.manage_combat(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\turn_management_tools.py", line 556, in manage_combat
    start_player_turn(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\turn_management_tools.py", line 93, in start_player_turn
    game_transitions.cycle_player_turn(global_manager, True)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\game_transitions.py", line 33, in cycle_player_turn
    turn_queue[0].selection_sound()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 277, in selection_sound
    self.global_manager.get('sound_manager').play_sound(random.choice(possible_sounds))
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\data_managers.py", line 808, in play_sound
    current_sound = pygame.mixer.Sound('sounds/' + file_name + '.wav')
FileNotFoundError: No file 'sounds/voices/ship_2.wav' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
