ERROR:root:No file 'graphics/misc/dice/0.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 1048, in set_image
    self.image = pygame.image.load('graphics/' + self.image_id)#.convert()
FileNotFoundError: No file 'graphics/misc/dice/0.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 926, in <module>
    main_loop.main_loop(global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 156, in main_loop
    current_button.on_click()#prioritize clicking buttons that appear above other buttons and don't press the ones
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\choice_notifications.py", line 181, in on_click
    super().on_click()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buttons.py", line 591, in on_click
    self.battalion.move(self.x_change, self.y_change, True)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\battalions.py", line 119, in move
    self.attempt_local_combat()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\battalions.py", line 133, in attempt_local_combat
    self.start_combat('attacking', defender)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 471, in start_combat
    self.combat() #later call next step when closing combat action notification instead of immediately
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 556, in combat
    self.display_die((die_x, 440), roll_list[0], 0, 6, 0, uses_minister) #die won't show result, so give inputs that make it green
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\pmobs.py", line 903, in display_die
    new_die = dice.die(scaling.scale_coordinates(coordinates[0], coordinates[1], self.global_manager), scaling.scale_width(100, self.global_manager), scaling.scale_height(100, self.global_manager), self.modes, 6,
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 48, in __init__
    super().__init__(coordinates, width, height, 'green', 'label', 'none', modes, image_id, global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buttons.py", line 55, in __init__
    self.image = images.button_image(self, self.width, self.height, image_id, self.global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 1010, in __init__
    self.set_image(image_id)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 1051, in set_image
    self.image = pygame.image.load('graphics/' + self.image_id)
FileNotFoundError: No file 'graphics/misc/dice/0.png' found in working directory 'C:\Users\vikto\Documents\Old computer files\SFA'.
