ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 36, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 197, in main_loop
    main_loop_tools.update_display(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop_tools.py", line 131, in update_display
    current_button.draw()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 187, in draw
    self.roll()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 154, in roll
    self.global_manager.get('current_dice_rolling_notification').remove()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\action_notifications.py", line 107, in remove
    super().remove()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\notifications.py", line 90, in remove
    notification_manager.notification_to_front(notification_manager.notification_queue[0])
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\data_managers.py", line 742, in notification_to_front
    new_notification = action_notifications.construction_notification(scaling.scale_coordinates(self.notification_x, self.notification_y, self.global_manager), scaling.scale_width(self.notification_width,
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\action_notifications.py", line 809, in __init__
    if global_manager.get('construction_result')[2] and global_manager.get('construction_result')[3] == 'mission': #if building mission success is True, play sound once dice roll finishes
IndexError: list index out of range
